#ifndef __STAN__MATH__SCALAR_HPP__
#define __STAN__MATH__SCALAR_HPP__

#include <stan/math/scalar/Phi.hpp>
#include <stan/math/scalar/Phi_approx.hpp>
#include <stan/math/scalar/as_bool.hpp>
#include <stan/math/scalar/bessel_first_kind.hpp>
#include <stan/math/scalar/bessel_second_kind.hpp>
#include <stan/math/scalar/binary_log_loss.hpp>
#include <stan/math/scalar/binomial_coefficient_log.hpp>
#include <stan/math/scalar/exp2.hpp>
#include <stan/math/scalar/falling_factorial.hpp>
#include <stan/math/scalar/fdim.hpp>
#include <stan/math/scalar/fma.hpp>
#include <stan/math/scalar/gamma_p.hpp>
#include <stan/math/scalar/gamma_q.hpp>
#include <stan/math/scalar/ibeta.hpp>
#include <stan/math/scalar/if_else.hpp>
#include <stan/math/scalar/int_step.hpp>
#include <stan/math/scalar/inv.hpp>
#include <stan/math/scalar/inv_sqrt.hpp>
#include <stan/math/scalar/inv_square.hpp>
#include <stan/math/scalar/inv_cloglog.hpp>
#include <stan/math/scalar/inv_logit.hpp>
#include <stan/math/scalar/is_uninitialized.hpp>
#include <stan/math/scalar/lbeta.hpp>
#include <stan/math/scalar/lmgamma.hpp>
#include <stan/math/scalar/log1m.hpp>
#include <stan/math/scalar/log1m_exp.hpp>
#include <stan/math/scalar/log1m_inv_logit.hpp>
#include <stan/math/scalar/log1p.hpp>
#include <stan/math/scalar/log1p_exp.hpp>
#include <stan/math/scalar/log2.hpp>
#include <stan/math/scalar/log_diff_exp.hpp>
#include <stan/math/scalar/log_falling_factorial.hpp>
#include <stan/math/scalar/log_inv_logit.hpp>
#include <stan/math/scalar/log_rising_factorial.hpp>
#include <stan/math/scalar/log_sum_exp.hpp>
#include <stan/math/scalar/logical_and.hpp>
#include <stan/math/scalar/logical_eq.hpp>
#include <stan/math/scalar/logical_gt.hpp>
#include <stan/math/scalar/logical_gte.hpp>
#include <stan/math/scalar/logical_lt.hpp>
#include <stan/math/scalar/logical_lte.hpp>
#include <stan/math/scalar/logical_negation.hpp>
#include <stan/math/scalar/logical_neq.hpp>
#include <stan/math/scalar/logical_or.hpp>
#include <stan/math/scalar/logit.hpp>
#include <stan/math/scalar/max.hpp>
#include <stan/math/scalar/min.hpp>
#include <stan/math/scalar/modified_bessel_first_kind.hpp>
#include <stan/math/scalar/modified_bessel_second_kind.hpp>
#include <stan/math/scalar/multiply_log.hpp>
#include <stan/math/scalar/rising_factorial.hpp>
#include <stan/math/scalar/square.hpp>
#include <stan/math/scalar/step.hpp>
#include <stan/math/scalar/value_of.hpp>

#endif
