#ifndef __STAN__DIFF__REV__SCALAR_HPP__
#define __STAN__DIFF__REV__SCALAR_HPP__

#include <stan/diff/rev/scalar/op/v_vari.hpp>
#include <stan/diff/rev/scalar/op/vv_vari.hpp>
#include <stan/diff/rev/scalar/op/vd_vari.hpp>
#include <stan/diff/rev/scalar/op/dv_vari.hpp>
#include <stan/diff/rev/scalar/op/vvv_vari.hpp>
#include <stan/diff/rev/scalar/op/vvd_vari.hpp>
#include <stan/diff/rev/scalar/op/vdv_vari.hpp>
#include <stan/diff/rev/scalar/op/vdd_vari.hpp>
#include <stan/diff/rev/scalar/op/dvv_vari.hpp>
#include <stan/diff/rev/scalar/op/dvd_vari.hpp>
#include <stan/diff/rev/scalar/op/ddv_vari.hpp>
#include <stan/diff/rev/scalar/op/precomp_v_vari.hpp>

#include <stan/diff/rev/scalar/operator_unary_negative.hpp>
#include <stan/diff/rev/scalar/operator_equal.hpp>
#include <stan/diff/rev/scalar/operator_not_equal.hpp>
#include <stan/diff/rev/scalar/operator_greater_than.hpp>
#include <stan/diff/rev/scalar/operator_greater_than_or_equal.hpp>
#include <stan/diff/rev/scalar/operator_less_than.hpp>
#include <stan/diff/rev/scalar/operator_less_than_or_equal.hpp>
#include <stan/diff/rev/scalar/operator_unary_not.hpp>
#include <stan/diff/rev/scalar/operator_unary_plus.hpp>
#include <stan/diff/rev/scalar/operator_addition.hpp>
#include <stan/diff/rev/scalar/operator_subtraction.hpp>
#include <stan/diff/rev/scalar/operator_multiplication.hpp>
#include <stan/diff/rev/scalar/operator_division.hpp>
#include <stan/diff/rev/scalar/operator_unary_increment.hpp>
#include <stan/diff/rev/scalar/operator_unary_decrement.hpp>

#include <stan/diff/rev/scalar/exp.hpp>
#include <stan/diff/rev/scalar/log.hpp>
#include <stan/diff/rev/scalar/log10.hpp>
#include <stan/diff/rev/scalar/sqrt.hpp>
#include <stan/diff/rev/scalar/pow.hpp>
#include <stan/diff/rev/scalar/inv.hpp>
#include <stan/diff/rev/scalar/inv_sqrt.hpp>
#include <stan/diff/rev/scalar/inv_square.hpp>
#include <stan/diff/rev/scalar/cos.hpp>
#include <stan/diff/rev/scalar/sin.hpp>
#include <stan/diff/rev/scalar/tan.hpp>
#include <stan/diff/rev/scalar/acos.hpp>
#include <stan/diff/rev/scalar/asin.hpp>
#include <stan/diff/rev/scalar/atan.hpp>
#include <stan/diff/rev/scalar/atan2.hpp>
#include <stan/diff/rev/scalar/cosh.hpp>
#include <stan/diff/rev/scalar/sinh.hpp>
#include <stan/diff/rev/scalar/tanh.hpp>
#include <stan/diff/rev/scalar/fabs.hpp>
#include <stan/diff/rev/scalar/floor.hpp>
#include <stan/diff/rev/scalar/ceil.hpp>
#include <stan/diff/rev/scalar/fmod.hpp>
#include <stan/diff/rev/scalar/abs.hpp>

#include <stan/diff/rev/scalar/operator_plus_equal.hpp>
#include <stan/diff/rev/scalar/operator_minus_equal.hpp>
#include <stan/diff/rev/scalar/operator_multiply_equal.hpp>
#include <stan/diff/rev/scalar/operator_divide_equal.hpp>

#include <stan/diff/rev/scalar/is_uninitialized.hpp>

#include <stan/diff/rev/scalar/acosh.hpp>
#include <stan/diff/rev/scalar/atanh.hpp>
#include <stan/diff/rev/scalar/asinh.hpp>
#include <stan/diff/rev/scalar/erf.hpp>
#include <stan/diff/rev/scalar/erfc.hpp>
#include <stan/diff/rev/scalar/exp2.hpp>
#include <stan/diff/rev/scalar/expm1.hpp>
#include <stan/diff/rev/scalar/lgamma.hpp>
#include <stan/diff/rev/scalar/log1p.hpp>
#include <stan/diff/rev/scalar/log1m.hpp>
#include <stan/diff/rev/scalar/fma.hpp>
#include <stan/diff/rev/scalar/fmax.hpp>
#include <stan/diff/rev/scalar/fmin.hpp>
#include <stan/diff/rev/scalar/gamma_p.hpp>
#include <stan/diff/rev/scalar/gamma_q.hpp>
#include <stan/diff/rev/scalar/hypot.hpp>
#include <stan/diff/rev/scalar/log2.hpp>
#include <stan/diff/rev/scalar/cbrt.hpp>
#include <stan/diff/rev/scalar/round.hpp>
#include <stan/diff/rev/scalar/trunc.hpp>
#include <stan/diff/rev/scalar/fdim.hpp>
#include <stan/diff/rev/scalar/tgamma.hpp>
#include <stan/diff/rev/scalar/step.hpp>
#include <stan/diff/rev/scalar/inv_cloglog.hpp>
#include <stan/diff/rev/scalar/Phi.hpp>
#include <stan/diff/rev/scalar/inv_logit.hpp>
#include <stan/diff/rev/scalar/Phi_approx.hpp>
#include <stan/diff/rev/scalar/log_loss.hpp>
#include <stan/diff/rev/scalar/log1m_exp.hpp>
#include <stan/diff/rev/scalar/log1p_exp.hpp>
#include <stan/diff/rev/scalar/log_diff_exp.hpp>
#include <stan/diff/rev/scalar/log_sum_exp.hpp>
#include <stan/diff/rev/scalar/square.hpp>
#include <stan/diff/rev/scalar/multiply_log.hpp>
#include <stan/diff/rev/scalar/if_else.hpp>
#include <stan/diff/rev/scalar/ibeta.hpp>
#include <stan/diff/rev/scalar/value_of.hpp>
#include <stan/diff/rev/scalar/as_bool.hpp>
#include <stan/diff/rev/scalar/owens_t.hpp>
#include <stan/diff/rev/scalar/bessel_first_kind.hpp>
#include <stan/diff/rev/scalar/bessel_second_kind.hpp>
#include <stan/diff/rev/scalar/modified_bessel_first_kind.hpp>
#include <stan/diff/rev/scalar/modified_bessel_second_kind.hpp>
#include <stan/diff/rev/scalar/falling_factorial.hpp>
#include <stan/diff/rev/scalar/rising_factorial.hpp>
#include <stan/diff/rev/scalar/log_falling_factorial.hpp>
#include <stan/diff/rev/scalar/log_rising_factorial.hpp>


#endif
